export const hotels = [
  {
    id: 14530975,
    name: "شقق العزيزية إن للشقق المخدومة",
    nameEn: "Al Aziziyah Inn Serviced Apartments",
    city: "نجران",
    cityEn: "Najran",
    country: "Saudi Arabia",
    flag: "🇸🇦",
  },
  {
    id: 13957949,
    name: "Asdan Hotel",
    nameEn: "Asdan Hotel",
    city: "الاحساء",
    cityEn: "Al Ahsa",
    country: "Saudi Arabia",
    flag: "🇸🇦",
  },
  {
    id: 12880429,
    name: "فندق قولد تاور",
    nameEn: "Gold Tower Hotel",
    city: "خميس مشيط",
    cityEn: "Khamis Mushait",
    country: "Saudi Arabia",
    flag: "🇸🇦",
  },
  {
    id: 12481799,
    name: "شقق راحتي جازان للشقق المخدومة",
    nameEn: "Rahti Jazan Serviced Apartments",
    city: "جازان",
    cityEn: "Jazan",
    country: "Saudi Arabia",
    flag: "🇸🇦",
  },
  {
    id: 12088623,
    name: "اماليا للوحدات السكنية المفروشة",
    nameEn: "Amalia Furnished Apartments",
    city: "خميس مشيط",
    cityEn: "Khamis Mushait",
    country: "Saudi Arabia",
    flag: "🇸🇦",
  },
  {
    id: 10640535,
    name: "شقق برج بيات للشقق الفندقية - Burj Bayat Hotel Apartments",
    nameEn: "Burj Bayat Hotel Apartments",
    city: "جيزان",
    cityEn: "Jazan",
    country: "Saudi Arabia",
    flag: "🇸🇦",
  },
  {
    id: 9840054,
    name: "شقق أروع القصور للشقق المخدومة",
    nameEn: "Arawa Al Qosor Serviced Apartments",
    city: "جدة",
    cityEn: "Jeddah",
    country: "Saudi Arabia",
    flag: "🇸🇦",
  },
  {
    id: 9219097,
    name: "همس المدى للشقق المخدومه",
    nameEn: "Hams Al Mada Serviced Apartments",
    city: "الأحساء",
    cityEn: "Al Ahsa",
    country: "Saudi Arabia",
    flag: "🇸🇦",
  },
  {
    id: 9213815,
    name: "شقق قصر الممشى للوحدات السكنية",
    nameEn: "Qasr Al Mamsha Apartments",
    city: "جازان",
    cityEn: "Jazan",
    country: "Saudi Arabia",
    flag: "🇸🇦",
  },
  {
    id: 8897994,
    name: "شقق كيان للشقق المخدومة",
    nameEn: "Kayan Serviced Apartments",
    city: "أبها",
    cityEn: "Abha",
    country: "Saudi Arabia",
    flag: "🇸🇦",
  },
  {
    id: 8818324,
    name: "فندق أورا ميلينيوم",
    nameEn: "Aura Millennium Hotel",
    city: "احد رفيده",
    cityEn: "Ahad Rafidah",
    country: "Saudi Arabia",
    flag: "🇸🇦",
  },
  {
    id: 8815372,
    name: "فندق البروج الفندقية",
    nameEn: "Al Burooj Hotel",
    city: "جازان",
    cityEn: "Jazan",
    country: "Saudi Arabia",
    flag: "🇸🇦",
  },
  {
    id: 8654145,
    name: "المنظر الجميل للشقق الفندقية",
    nameEn: "Al Manzar Al Jameel Hotel Apartments",
    city: "الجبيل",
    cityEn: "Jubail",
    country: "Saudi Arabia",
    flag: "🇸🇦",
  },
  {
    id: 8279777,
    name: "شقق ركن مدهال جازان للشقق المخدومة",
    nameEn: "Rukn Madhhal Jazan Serviced Apartments",
    city: "جازان",
    cityEn: "Jazan",
    country: "Saudi Arabia",
    flag: "🇸🇦",
  },
  {
    id: 7833052,
    name: "شاليهات سرايا ان لبيوت العطلات",
    nameEn: "Saraya Inn Holiday Chalets",
    city: "جيزان",
    cityEn: "Jazan",
    country: "Saudi Arabia",
    flag: "🇸🇦",
  },
  {
    id: 7246165,
    name: "شاليهات رميس للعائلات",
    nameEn: "Ramees Family Chalets",
    city: "أبها",
    cityEn: "Abha",
    country: "Saudi Arabia",
    flag: "🇸🇦",
  },
  {
    id: 6512487,
    name: "شقق كيان للشقق المخدومه",
    nameEn: "Kayan Serviced Apartments",
    city: "جدة",
    cityEn: "Jeddah",
    country: "Saudi Arabia",
    flag: "🇸🇦",
  },
  {
    id: 5548610,
    name: "شقق أمواج للشقق المخدومة",
    nameEn: "Amwaj Serviced Apartments",
    city: "الخبر",
    cityEn: "Khobar",
    country: "Saudi Arabia",
    flag: "🇸🇦",
  },
  {
    id: 4672486,
    name: "شقق نواميس للشقق المخدومة",
    nameEn: "Nawamees Serviced Apartments",
    city: "خميس مشيط",
    cityEn: "Khamis Mushait",
    country: "Saudi Arabia",
    flag: "🇸🇦",
  },
  {
    id: 3860441,
    name: "فندق ان فيولا",
    nameEn: "Enviola Hotel",
    city: "جيزان",
    cityEn: "Jazan",
    country: "Saudi Arabia",
    flag: "🇸🇦",
  },
  {
    id: 2930282,
    name: "جراند خيال للشقق المخدومه",
    nameEn: "Grand Khayal Serviced Apartments",
    city: "جدة",
    cityEn: "Jeddah",
    country: "Saudi Arabia",
    flag: "🇸🇦",
  },
  {
    id: 2043094,
    name: "Procare Apart hotel",
    nameEn: "Procare Apart Hotel",
    city: "جدة",
    cityEn: "Jeddah",
    country: "Saudi Arabia",
    flag: "🇸🇦",
  },
  {
    id: 1667716,
    name: "شقق أمواج للشقق المخدومه",
    nameEn: "Amwaj Serviced Apartments",
    city: "الجبيل",
    cityEn: "Jubail",
    country: "Saudi Arabia",
    flag: "🇸🇦",
  },
  {
    id: 1267001,
    name: "Burj Al Almas",
    nameEn: "Burj Al Almas",
    city: "الجبيل",
    cityEn: "Jubail",
    country: "Saudi Arabia",
    flag: "🇸🇦",
  },
  {
    id: 1168266,
    name: "جراند خيال للشقق المخدومة",
    nameEn: "Grand Khayal Serviced Apartments",
    city: "أبها",
    cityEn: "Abha",
    country: "Saudi Arabia",
    flag: "🇸🇦",
  },
  {
    id: 13127970,
    name: "اللؤلؤة البيضاء",
    nameEn: "Al Louloua Al Baida",
    city: "خميس مشيط",
    cityEn: "Khamis Mushait",
    country: "Saudi Arabia",
    flag: "🇸🇦",
  },
  {
    id: 11112222333,
    name: "مرسى جيزان",
    nameEn: "Marsa Jazan",
    city: "جيزان",
    cityEn: "Jazan",
    country: "Saudi Arabia",
    flag: "🇸🇦",
  },
  {
    id: 3322223323,
    name: "زهرة الباهية",
    nameEn: "Zahret Al Bahiah",
    city: "نجران",
    cityEn: "Najran",
    country: "Saudi Arabia",
    flag: "🇸🇦",
  },

  {
    id: 15413383,
    name: "فندق اجنحة السمو إن",
    nameEn: "Al Samo Inn Suites",
    city: "أحد المسارحة",
    cityEn: "Ahad Al Masarihah",
    country: "Saudi Arabia",
    flag: "🇸🇦",
  },
  {
    id: 15413448,
    name: "فندق اجنحة السمو إن",
    nameEn: "Al Samo Inn Suites",
    city: "أبوعريش",
    cityEn: "Abu Arish",
    country: "Saudi Arabia",
    flag: "🇸🇦",
  },

  //
  {
    id: 15780945,
    name: "فندق اجنحة السمو ابو عريش",
    nameEn: "Al Samo Suites abu arish",
    city: "أبوعريش",
    cityEn: "Abu Arish",
    country: "Saudi Arabia",
    flag: "🇸🇦",
  },
  {
    id: 15780862,
    name: "فندق اجنحة السمو الدغارير",
    nameEn: "Al Samo Suites aldagharir",
    city: "الدغارير",
    cityEn: "aldagharir",
    country: "Saudi Arabia",
    flag: "🇸🇦",
  },
  {
    id: 15781098,
    name: "فندق اجنحة السمو العيدابي",
    nameEn: "Al Samo Suites ediby",
    city: "العيدابي",
    cityEn: "ediby",
    country: "Saudi Arabia",
    flag: "🇸🇦",
  },
  {
    id: 15780621,
    name: "فندق اجنحة السمو جيزان",
    nameEn: "Al Samo Suites Jizan",
    city: "جيزان",
    cityEn: "Jizan",
    country: "Saudi Arabia",
    flag: "🇸🇦",
  },
  {
    id: 8542022,
    name: "فندق بيرلي",
    nameEn: "Pearly Hotel",
    city: "ابها",
    cityEn: "Abha",
    country: "Saudi Arabia",
    flag: "🇸🇦",
  },
  {
    id: 8340708,
    name: "شقق جلف نايت",
    nameEn: "gulf night",
    city: "الرياض",
    cityEn: "Riyadh",
    country: "Saudi Arabia",
    flag: "🇸🇦",
  },
  {
    id: 2331625,
    name: "شقق اورينتال وورلد",
    nameEn: "Ornital World Serviced Apartments",
    city: "وادي الدواسر",
    cityEn: "Wadi Al Dawasir",
    country: "Saudi Arabia",
    flag: "🇸🇦",
  },
  {
    id: 1234789011,
    name: "مجموعة فنادق قصر الملوك",
    nameEn: "Kings palace hotel",
    city: "القاهرة",
    cityEn: "Cairo",
    country: "Egypt",
    flag: "EG",
  },
  {
    id: 13777897,
    name: "مجموعة فنادق فيدا بيراميدز",
    nameEn: "Vida pyramids hotel",
    city: "الجيزة",
    cityEn: "Giza",
    country: "Egypt",
    flag: "EG",
  },
];
